import Head from "next/head";
import styles from "./styles.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ivandcfit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <img className={styles.img} src="/header.jpg" alt="as" /> */}
      </main>
    </div>
  );
}
